# Generated by Django 4.2.4 on 2023-08-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country_made', models.CharField(max_length=50)),
                ('wheels', models.PositiveIntegerField()),
                ('horsepower', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('color', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_app.category')),
            ],
        ),
    ]
